import test from 'node:test';
import assert from 'node:assert/strict';
import api, { LogoOrder, PRICE } from '../../logo-worker/index.mjs';
class Storage {
 data = new Map(); tail = Promise.resolve();
 async get(k){return structuredClone(this.data.get(k));}
 async put(k,v){this.data.set(k,structuredClone(v));}
 async transaction(fn){const result=this.tail.then(()=>fn(this));this.tail=result.catch(()=>{});return result;}
}
const env={SALES_ENABLED:'true',RECRAFT_API_TOKEN:'fake',TOSS_CLIENT_KEY:'test_ck_fake',TOSS_SECRET_KEY:'test_sk_fake'};
const id='logo_'+'a'.repeat(32), tokenHash='fake-hash';
const req=(action,data)=>new Request('https://internal/'+action,{method:data?'POST':'GET',headers:{'x-token-hash':tokenHash},...(data?{body:JSON.stringify(data)}:{})});
async function order(){const storage=new Storage(),obj=new LogoOrder({storage},env);await obj.fetch(req('init',{id,tokenHash,brief:{name:'상호',mood:'minimal',color:'#112233'}}));return {obj,storage};}
const payment={status:'DONE',orderId:id,totalAmount:PRICE,balanceAmount:PRICE,currency:'KRW'};
const rid=()=>crypto.randomUUID();
const svg='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 10"><circle cx="5" cy="5" r="4"/></svg>';
const mock=async(url)=>new Response(JSON.stringify(String(url).includes('recraft')?{data:[{b64_json:btoa(svg)}]}:payment));
test('disabled sales refuses order creation without provider calls',async()=>{const r=await api.fetch(new Request('https://x/logo/api/orders',{method:'POST',body:'{}'}),{ORDERS:{},SALES_ENABLED:'false'});assert.equal(r.status,503);});
test('wrong token and unpaid generation cannot access paid API',async()=>{const {obj}=await order();assert.equal((await obj.fetch(new Request('https://internal/status'))).status,404);assert.equal((await obj.fetch(req('generate',{requestId:rid()}))).status,402);});
test('forged amount rejected before confirm; idempotent confirm preserves credits',async()=>{const {obj,storage}=await order();let calls=0;const old=globalThis.fetch;globalThis.fetch=async()=>{calls++;return new Response(JSON.stringify(payment));};try{assert.equal((await obj.fetch(req('confirm',{orderId:id,amount:1,paymentKey:'pay'}))).status,400);assert.equal(calls,0);assert.equal((await obj.fetch(req('confirm',{orderId:id,amount:PRICE,paymentKey:'pay'}))).status,200);await obj.fetch(req('confirm',{orderId:id,amount:PRICE,paymentKey:'pay'}));assert.equal(calls,1);assert.equal((await storage.get('order')).remaining,8);}finally{globalThis.fetch=old;}});
test('generation replay does not bill again; quota never exceeds eight',async()=>{const {obj,storage}=await order();let o=await storage.get('order');o.status='paid';o.paymentKey='pay';await storage.put('order',o);let generations=0;const old=globalThis.fetch;globalThis.fetch=async(url)=>{if(String(url).includes('recraft'))generations++;return mock(url);};try{const requestId=rid();await obj.fetch(req('generate',{requestId}));await obj.fetch(req('generate',{requestId}));assert.equal(generations,1);for(let i=0;i<7;i++)assert.equal((await obj.fetch(req('generate',{requestId:rid()}))).status,200);assert.equal((await obj.fetch(req('generate',{requestId:rid()}))).status,409);assert.equal(generations,8);const result=await (await obj.fetch(req('status'))).json();assert.equal(result.remaining,0);assert.equal(result.results[0].svg,svg);}finally{globalThis.fetch=old;}});
test('provider failure restores quantity, records attempt, and stops replay',async()=>{const {obj,storage}=await order();const o=await storage.get('order');o.status='paid';o.paymentKey='pay';await storage.put('order',o);const old=globalThis.fetch;globalThis.fetch=async url=>String(url).includes('recraft')?new Response('{}',{status:500}):mock(url);try{const requestId=rid();assert.equal((await obj.fetch(req('generate',{requestId}))).status,502);const failed=await storage.get('order');assert.equal(failed.remaining,8);assert.equal(failed.attempts,1);assert.equal(failed.jobs[requestId].state,'failed');}finally{globalThis.fetch=old;}});
test('refund state refuses fresh generation',async()=>{const {obj,storage}=await order();const o=await storage.get('order');o.status='paid';o.paymentKey='pay';await storage.put('order',o);const old=globalThis.fetch;globalThis.fetch=async()=>new Response(JSON.stringify({...payment,status:'CANCELED',balanceAmount:0}));try{assert.equal((await obj.fetch(req('generate',{requestId:rid()}))).status,402);assert.equal((await storage.get('order')).remaining,8);}finally{globalThis.fetch=old;}});
test('simultaneous requests allow only one provider generation',async()=>{const {obj,storage}=await order();const o=await storage.get('order');o.status='paid';o.paymentKey='pay';await storage.put('order',o);let calls=0,release;const wait=new Promise(r=>release=r),old=globalThis.fetch;globalThis.fetch=async url=>{if(String(url).includes('recraft')){calls++;await wait;}return mock(url);};try{const first=obj.fetch(req('generate',{requestId:rid()}));while(!calls)await new Promise(r=>setTimeout(r,1));const second=await obj.fetch(req('generate',{requestId:rid()}));assert.equal(second.status,409);release();assert.equal((await first).status,200);assert.equal(calls,1);}finally{globalThis.fetch=old;}});
