import { categories,validateOptions } from '../../../photo-app/catalog.mjs';
import { zipSync } from 'fflate';
const $=selector=>document.querySelector(selector),element=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
let category='portrait',queue=[],results=[],busy=false,styles=[];
const storageKey='sajin-kureomi:styles:v1';
try{const saved=JSON.parse(localStorage.getItem(storageKey)??'[]');if(Array.isArray(saved))styles=saved.slice(0,20).filter(s=>{try{validateOptions(s);return typeof s.name==='string'&&s.name.length<=40&&typeof s.id==='string';}catch{return false;}});}catch{/* Storage is optional. */}
const status=message=>{$('#status').textContent=message;};
const choices=()=>({category,preset:$('#preset').value,strength:Number($('#strength').value)});
function setCategory(){for(const b of $('#categories').children)b.setAttribute('aria-pressed',String(b.dataset.category===category));const c=categories[category];$('#category-title').textContent=c.name;$('#category-description').textContent=c.description;$('#preset').replaceChildren(...Object.entries(c.presets).map(([id,name])=>new Option(name,id)));}
function renderStyles(){const select=$('#saved-style'),previous=select.value;select.replaceChildren(new Option('스타일 선택',''),...styles.map(s=>new Option(s.name,s.id)));select.value=previous;$('#delete-style').hidden=!select.value;}
function persistStyles(next){try{localStorage.setItem(storageKey,JSON.stringify(next));styles=next;renderStyles();return true;}catch{status('이 브라우저에 스타일을 저장할 수 없습니다. 사진 보정은 계속 사용할 수 있어요.');return false;}}
function render(){
  $('#queue').replaceChildren(...queue.map((item,index)=>{const row=element('li'),text=element('span',`${item.file.name}${item.message?' · '+item.message:''}`),remove=element('button','빼기');remove.disabled=busy;remove.onclick=()=>{queue.splice(index,1);render();};row.append(text,remove);return row;}));
  $('#estimate').textContent=queue.length?`${queue.length}장 선택 · 무료로 보정합니다.`:'사진을 선택해주세요. 보정과 다운로드는 무료입니다.';
  $('#process').disabled=busy||!queue.length;$('#process').textContent=busy?'사진을 다듬고 있어요…':queue.length?`${queue.length}장 무료 보정`:'보정하기';
  for(const id of ['files','preset','strength','saved-style','save-style','delete-style','clear-results'])$('#'+id).disabled=busy;
  for(const button of $('#categories').children)button.disabled=busy;
  $('#results-section').hidden=!results.length;$('#download-all').disabled=busy||!results.length;
  $('#results').replaceChildren(...results.map(result=>{const card=element('article',undefined,'result-card'),top=element('div',undefined,'result-top');top.append(element('strong',`${categories[result.options.category].name} · ${categories[result.options.category].presets[result.options.preset]}`),element('span',`${result.width}×${result.height}`));
    const compare=element('div',undefined,'compare'),after=element('img'),before=element('img',undefined,'before');after.src=result.outputURL;after.alt='보정 결과';before.src=result.originalURL;before.alt='보정 전 사진';const tags=element('div',undefined,'compare-tags');tags.append(element('span','보정 전'),element('span','보정 후'));compare.append(after,before,tags);
    const slider=element('input');slider.type='range';slider.min='0';slider.max='100';slider.value='50';slider.id='compare-'+result.id;const label=element('label','전후 비교');label.htmlFor=slider.id;slider.oninput=()=>{before.style.clipPath=`inset(0 ${100-Number(slider.value)}% 0 0)`;after.style.clipPath=`inset(0 0 0 ${slider.value}%)`;};
    const actions=element('div',undefined,'result-actions'),download=element('a','PNG 다운로드');download.href=result.outputURL;download.download=result.name;
    const remove=element('button','지우기','text-button danger');remove.disabled=busy;remove.onclick=()=>{dispose(result);results=results.filter(r=>r.id!==result.id);render();status('작업 화면에서 사진을 지웠습니다. 다운로드한 파일은 기기에 남습니다.');};actions.append(download,remove);card.append(top,compare,label,slider,actions);return card;}));
}
function dispose(result){URL.revokeObjectURL(result.originalURL);URL.revokeObjectURL(result.outputURL);}
function add(files){if(busy)return;let message='';for(const file of files){if(queue.length>=10){message='한 번에 최대 10장까지 선택할 수 있습니다.';break;}if(!['image/jpeg','image/png','image/webp'].includes(file.type)||!file.size||file.size>10*1024*1024){message='JPG·PNG·WebP, 장당 10MB 이하 파일을 선택해주세요.';continue;}queue.push({file});}$('#files').value='';status(message);render();}
function run(file,options){return new Promise((resolve,reject)=>{let worker;try{worker=new Worker(new URL('./worker.js',import.meta.url),{type:'module'});}catch{return reject(new Error('사진 보정을 지원하는 최신 브라우저로 열어주세요.'));}const timer=setTimeout(()=>finish(new Error('처리 시간이 길어 중단했습니다. 더 작은 사진으로 다시 시도해주세요.')),45000);function finish(error,result){clearTimeout(timer);worker.terminate();error?reject(error):resolve(result);}worker.onmessage=({data})=>finish(data.error?new Error(data.error):null,data.result);worker.onerror=()=>finish(new Error('사진 처리에 실패했습니다. 최신 브라우저에서 더 작은 사진으로 다시 시도해주세요.'));worker.postMessage({file,options});});}
for(const[id,value]of Object.entries(categories)){const button=element('button',undefined,'category');button.dataset.category=id;button.append(element('strong',value.name),element('span',value.description));button.onclick=()=>{category=id;setCategory();};$('#categories').append(button);}
setCategory();renderStyles();render();
$('#files').onchange=e=>add(e.target.files);$('#dropzone').ondragover=e=>{e.preventDefault();$('#dropzone').classList.add('dragging');};$('#dropzone').ondragleave=()=>$('#dropzone').classList.remove('dragging');$('#dropzone').ondrop=e=>{e.preventDefault();$('#dropzone').classList.remove('dragging');add(e.dataTransfer.files);};
$('#strength').oninput=e=>{$('#strength-value').value=`${e.target.value}%`;};
$('#save-style').onclick=()=>{if(styles.length>=20){status('스타일은 최대 20개까지 저장할 수 있습니다.');return;}const name=prompt('저장할 스타일 이름을 입력해주세요.');if(!name?.trim())return;if(name.trim().length>40){status('스타일 이름은 40자 이하로 입력해주세요.');return;}if(persistStyles([...styles,{id:crypto.randomUUID(),name:name.trim(),...choices()}]))status('이 브라우저에 스타일을 저장했습니다.');};
$('#saved-style').onchange=e=>{const style=styles.find(s=>s.id===e.target.value);$('#delete-style').hidden=!style;if(!style)return;category=style.category;setCategory();$('#preset').value=style.preset;$('#strength').value=style.strength;$('#strength-value').value=`${style.strength}%`;};
$('#delete-style').onclick=()=>{if(persistStyles(styles.filter(s=>s.id!==$('#saved-style').value)))status('저장한 스타일을 지웠습니다.');};
$('#process').onclick=async()=>{if(busy||!queue.length)return;if(results.length+queue.length>20){status('결과는 최대 20장까지 보관할 수 있습니다. 먼저 다운로드한 사진을 지워주세요.');return;}busy=true;render();const options=choices(),failed=[];let completed=0;for(const item of queue){status(`${completed+failed.length+1}/${queue.length}장 보정 중…`);try{const result=await run(item.file,options),id=crypto.randomUUID();if(results.reduce((n,r)=>n+r.original.size+r.output.size,0)+result.original.size+result.output.size>100*1024*1024)throw new Error('작업 사진이 100MB를 넘습니다. 저장한 결과를 지우고 다시 시도해주세요.');results.push({...result,id,options:{...options},name:`sajin-kureomi-${id.slice(0,8)}.png`,originalURL:URL.createObjectURL(result.original),outputURL:URL.createObjectURL(result.output)});completed++;}catch(error){item.message=error.message;failed.push(item);}}queue=failed;busy=false;render();status(`${completed}장 보정 완료.${failed.length?' 처리하지 못한 사진의 안내를 확인해주세요.':' 아래에서 비교하고 다운로드하세요.'}`);};
$('#clear-results').onclick=()=>{results.forEach(dispose);results=[];queue=[];render();status('작업 사진을 모두 지웠습니다.');};
$('#download-all').onclick=async()=>{const button=$('#download-all');button.disabled=true;try{const selected=[...results],total=selected.reduce((n,r)=>n+r.output.size,0);if(total>60*1024*1024)throw new Error('묶음이 60MB를 넘습니다. 사진별 PNG로 다운로드해주세요.');const files={};for(const result of selected)files[result.name]=new Uint8Array(await result.output.arrayBuffer());const url=URL.createObjectURL(new Blob([zipSync(files,{level:0})],{type:'application/zip'})),link=element('a');link.href=url;link.download='sajin-kureomi.zip';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}catch(error){status(error.message);}finally{button.disabled=false;}};
